const express=require('express');const path=require('path');const fs=require('fs');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const cookieParser=require('cookie-parser');const multer=require('multer');const Database=require('better-sqlite3');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'bca-job-portal-change-this-secret';
fs.mkdirSync(path.join(__dirname,'uploads'),{recursive:true});
const db=new Database(path.join(__dirname,'jobportal.db'));db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('student','employer','admin')),created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS jobs(id INTEGER PRIMARY KEY AUTOINCREMENT,employer_id INTEGER NOT NULL,title TEXT NOT NULL,company TEXT NOT NULL,location TEXT NOT NULL,job_type TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,skills TEXT DEFAULT '',salary TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(employer_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS applications(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id INTEGER NOT NULL,student_id INTEGER NOT NULL,resume TEXT,cover_letter TEXT DEFAULT '',status TEXT DEFAULT 'Applied',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(job_id,student_id),FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE,FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE CASCADE);`);
const seed=db.prepare('SELECT COUNT(*) c FROM users').get().c;if(!seed){const pw=bcrypt.hashSync('password123',10);const u=db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)');const emp=u.run('Demo Employer','employer@demo.com',pw,'employer').lastInsertRowid;u.run('Demo Student','student@demo.com',pw,'student');u.run('Administrator','admin@demo.com',pw,'admin');const j=db.prepare('INSERT INTO jobs(employer_id,title,company,location,job_type,category,description,skills,salary) VALUES(?,?,?,?,?,?,?,?,?)');j.run(emp,'Junior Web Developer','TechNova Solutions','Remote / Ludhiana','Full-time','Web Development','Build responsive websites and collaborate with the product team. Great role for fresh graduates.','HTML, CSS, JavaScript, Git','₹3–5 LPA');j.run(emp,'Python Intern','DataCraft Labs','Chandigarh','Internship','Python','Work with Python automation and data-processing projects under senior developers.','Python, SQL, Git','₹12,000/month');}
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));
const storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,path.join(__dirname,'uploads')),filename:(r,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/\.(pdf|doc|docx)$/i.test(f.originalname))});
function auth(req,res,next){const token=req.cookies.token||req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({error:'Please log in'});try{req.user=jwt.verify(token,SECRET);next()}catch(e){res.status(401).json({error:'Session expired'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Access denied'})}
app.post('/api/register',(req,res)=>{const {name,email,password,role}=req.body;if(!name||!email||!password||!['student','employer'].includes(role))return res.status(400).json({error:'Complete all required fields'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters'});try{const info=db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run(name,email.toLowerCase(),bcrypt.hashSync(password,10),role);res.json({message:'Account created',id:info.lastInsertRowid})}catch(e){res.status(400).json({error:'Email already registered'})}});
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get((req.body.email||'').toLowerCase());if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Invalid email or password'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'7d'});res.cookie('token',token,{httpOnly:true,sameSite:'lax',maxAge:7*86400000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/logout',(req,res)=>{res.clearCookie('token');res.json({message:'Logged out'})});app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/jobs',(req,res)=>{const q=(req.query.q||'').trim(),type=req.query.type||'',cat=req.query.category||'';let sql=`SELECT j.*,u.name employer_name,(SELECT COUNT(*) FROM applications a WHERE a.job_id=j.id) applicants FROM jobs j JOIN users u ON u.id=j.employer_id WHERE 1=1`,p=[];if(q){sql+=` AND (j.title LIKE ? OR j.company LIKE ? OR j.skills LIKE ? OR j.location LIKE ?)`;p.push('%'+q+'%','%'+q+'%','%'+q+'%','%'+q+'%')}if(type){sql+=' AND j.job_type=?';p.push(type)}if(cat){sql+=' AND j.category=?';p.push(cat)}sql+=' ORDER BY j.created_at DESC';res.json({jobs:db.prepare(sql).all(...p)})});
app.post('/api/jobs',auth,role('employer','admin'),(req,res)=>{const {title,company,location,job_type,category,description,skills,salary}=req.body;if(!title||!company||!location||!job_type||!category||!description)return res.status(400).json({error:'Fill all required job fields'});const id=db.prepare('INSERT INTO jobs(employer_id,title,company,location,job_type,category,description,skills,salary) VALUES(?,?,?,?,?,?,?,?,?)').run(req.user.id,title,company,location,job_type,category,description,skills||'',salary||'').lastInsertRowid;res.json({message:'Job posted',id})});
app.delete('/api/jobs/:id',auth,role('employer','admin'),(req,res)=>{const j=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!j)return res.status(404).json({error:'Job not found'});if(req.user.role!=='admin'&&j.employer_id!==req.user.id)return res.status(403).json({error:'Not your job'});db.prepare('DELETE FROM jobs WHERE id=?').run(req.params.id);res.json({message:'Job deleted'})});
app.post('/api/jobs/:id/apply',auth,role('student'),upload.single('resume'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Resume PDF/DOC/DOCX is required'});try{db.prepare('INSERT INTO applications(job_id,student_id,resume,cover_letter) VALUES(?,?,?,?)').run(req.params.id,req.user.id,req.file.filename,req.body.cover_letter||'');res.json({message:'Application submitted'})}catch(e){if(req.file)fs.unlinkSync(req.file.path);res.status(400).json({error:'You have already applied for this job'})}});
app.get('/api/applications/mine',auth,role('student'),(req,res)=>res.json({applications:db.prepare(`SELECT a.*,j.title,j.company,j.location FROM applications a JOIN jobs j ON j.id=a.job_id WHERE a.student_id=? ORDER BY a.created_at DESC`).all(req.user.id)}));
app.get('/api/employer/applications',auth,role('employer','admin'),(req,res)=>{const extra=req.user.role==='admin'?'':' AND j.employer_id='+Number(req.user.id);res.json({applications:db.prepare(`SELECT a.*,j.title,j.company,u.name student_name,u.email student_email FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users u ON u.id=a.student_id WHERE 1=1${extra} ORDER BY a.created_at DESC`).all()})});
app.patch('/api/applications/:id',auth,role('employer','admin'),(req,res)=>{const allowed=['Applied','Shortlisted','Interview','Rejected','Selected'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});const a=db.prepare('SELECT a.*,j.employer_id FROM applications a JOIN jobs j ON j.id=a.job_id WHERE a.id=?').get(req.params.id);if(!a||(req.user.role!=='admin'&&a.employer_id!==req.user.id))return res.status(403).json({error:'Access denied'});db.prepare('UPDATE applications SET status=? WHERE id=?').run(req.body.status,req.params.id);res.json({message:'Status updated'})});
app.get('/api/resume/:filename',auth,(req,res)=>{const a=db.prepare('SELECT * FROM applications WHERE resume=?').get(req.params.filename);if(!a||(req.user.role==='student'&&a.student_id!==req.user.id))return res.status(403).end();const f=path.join(__dirname,'uploads',req.params.filename);if(!fs.existsSync(f))return res.status(404).end();res.download(f)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Job Portal running at http://localhost:${PORT}`));
